### Variables 
@apiurl = http://localhost:3333

### GET users
GET {{apiurl}}/users HTTP/1.1

### POST users
POST {{apiurl}}/users HTTP/1.1
Content-Type: application/json

{
   "name":"Evenilson",
   "email":"evenilson@acme.com",
   "password":"123344"
}

### POST sessions/password
POST {{apiurl}}/sessions/password HTTP/1.1
Content-Type: application/json

{
   "email":"evenilson@acme.com"
}


### GET profile
GET {{apiurl}}/profile HTTP/1.1
# Content-Type: application/json
Authorization: Bearer eyaJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YjRiNzJjMS1iYTFiLTRjODgtYjc3My1mNmY2Y2Y3ZDllOWEiLCJpYXQiOjE3NTI5NDQzNzgsImV4cCI6MTc1MzU0OTE3OH0.vLm8xcVNJA1zsH8QEvN6Cg4WTSpR6m1PiCubG0VtsTo

